### ISSUE TITLE
Adding Members to claimed chunk does nothing

### ISSUE THREAD

**Issue by MisterSmileyFace** [alfuken/chunk_claim#6]
I claimed a chunk, then added a member to the chunk. Then got info on chunk to verify that it reflected the new memeber added, which it did. Member can not interact with anything while in chunk. It reflects the member is part of the chunk, but act like they are not.
 
Minecraft version 1.14.4 
Modpack ATM4 build 1.6

**Comment by polo123qwe** [comment]
Make sure the name respects uppercase

**Comment by MisterSmileyFace** [comment]
I add the name with the correct uppercase yet once the member is added and on the list it is no longer showing the uppercase reflected.

**Comment by MisterSmileyFace** [comment]
In case the last response was confusing, it was added with the correct uppercase and is still not working. Nor does it save the uppercase after added to the list.

**Comment by darkt1981** [comment]
mod doesnt support Capital letters, when you wanna add some that has capital laters it will now allow it, this is a bug and needs fixing.

**Comment by Herostere** [comment]
As said before, the mod doesn't support capital letters. Is it possible for you to fix that? Thank you.

**Comment by kreezxil** [comment]
@polo123qwe is this a real issue? I want to add your mod to resolve our servers need to build massive rail systems that non-teamed players can't arse with, except only those that are teamed.

**Comment by MisterSmileyFace** [comment]
I have confirmed that it works with all lowercase names, but if the user being added has an uppercase letter in the name, it will add it will all lowercase and not work.

**Comment by MisterSmileyFace** [comment]
I just downloaded the new version excited to see if it fixes the capatilizaon issues, and sadly it does not. Same issue as above still exists.

**Comment by polo123qwe** [comment]
Issue should be fixed in the latest version

**Comment by MisterSmileyFace** [comment]
If you are talking about 2.7.3, it is not for me. That was the one I downloaded a day ago hoping it was.

**Comment by MisterSmileyFace** [comment]
If it helps, I am adding it to the ATM4 2.3 version on 1.14.4

**Comment by Herostere** [comment]
Yep, sadly still not working. Exactly what MisterSmileyFace have said before. The upper cases do not work. 
Hope you'll be able to find how to fix the issue. I've take look at your code but I couldn't find the way to fix that.

**Comment by darkt1981** [comment]
Oke not sure if this helps but i did some testing.

- inside the chunk storage file it does save names in capital, so thats not the issue, seems like the issue is in the reading the file back and or adding extra people to your claim.

investigating it futher, will keep you updated.

**Comment by Szum123321** [comment]
So I played with this code and I found bug.
It is lockated in file CommandAddMemebr.java

Code now looks like this:
```java
public class CommandAddMember {
    public static ArgumentBuilder<CommandSource, ?> register() {
        return Commands.literal("add_member")
                .requires(cs -> cs.hasPermissionLevel(0))
                .then(Commands.argument("member", Argument.argument())
                        .executes(ctx -> CommandAddMember.executeCommand(ctx.getSource(), ctx.getArgument("member", String.class)))
                );
    }

    private static int executeCommand(CommandSource command, String name) {
        ServerPlayerEntity player = UtilsCommands.getServerPlayerEntity(command);

        if(player == null) {
            return 0;
        }

        command.sendFeedback(new StringTextComponent(ClaimManager.addMember(player, name)), true);

        return 1;
    }
}
```
BUT methode argument() in class Argument returns string in lower case. Always
```java
commands.add(command.toString().toLowerCase());
```
(And also displays some weird suggestions.)
So this is what I did:
```java
public class CommandAddMember {
    public static ArgumentBuilder<CommandSource, ?> register() {
        return Commands.literal("add_member")
                .requires(cs -> cs.hasPermissionLevel(0))
                .then(Commands.argument("member", EntityArgument.players())
                        .executes(ctx -> CommandAddMember.executeCommand(ctx.getSource(), EntityArgument.getPlayer(ctx, "member")))
                );
    }

    private static int executeCommand(CommandSource command, ServerPlayerEntity member) {
        ServerPlayerEntity player = UtilsCommands.getServerPlayerEntity(command);

        if(player == null) {
            return 0;
        }

        command.sendFeedback(new StringTextComponent(ClaimManager.addMember(player, member.getName().getString())), true);

        return 1;
    }
}
```
Now, when you want to type-in player's nick it displayes currently available players.

**Comment by alfuken** [comment]
Cool! 👍 Can you create a PR? I'll merge and release.

**Comment by Szum123321** [comment]
Sorry, but I don't know how to.

**Comment by alfuken** [comment]
1. Click the "Fork" button in top right corner, that will make a copy of the repository to your account. 2. Download it (checkout) to your local machine
3. make necessary edits
4. do a commit
5. push the changes to your repository
6. Click on "Pull requests" menu item
7. Choose source and destination
8. Add "Reviewers" on the right
9. Click "Create pull request"

Steps 1-5 can be omitted if you have to edit only one file - you can do so using Github's file editing tool. For that, in your the repository navigate to the file in question and click "Edit", then make changes, fill in change description, choose option "Create a new branch for this commit and start a pull request.", and submit changes.

**Comment by MisterSmileyFace** [comment]
Thank you guys for working on this, I will be super excited when I can make my server live and this is the last step!Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Bohdan Schepansky <notifications@github.com> Date: 11/25/19  3:19 PM  (GMT-06:00) To: alfuken/chunk_claim <chunk_claim@noreply.github.com> Cc: MisterSmileyFace <amcwethy@gmx.com>, Author <author@noreply.github.com> Subject: Re: [alfuken/chunk_claim] Adding Members to claimed chunk does nothing (#6) 
Click the "Fork" button in top right corner, that will make a copy of the repository to your account. 2. Download it (checkout) to your local machine
make necessary edits
do a commit
push the changes to your repository
Click on "Pull requests" menu item
Choose source and destination
Add "Reviewers" on the right
Click "Create pull request"

Steps 1-5 can be omitted if you have to edit only one file - you can do so using Github's file editing tool. For that, in your the repository navigate to the file in question and click "Edit", then make changes, fill in change description, choose option "Create a new branch for this commit and start a pull request.", and submit changes.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/alfuken/chunk_claim/issues/6?email_source=notifications\u0026email_token=AJSS6OFULFY3EU7FJICBSMDQVQ6MNA5CNFSM4JGPJIPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFD2SGQ#issuecomment-558344474",
"url": "https://github.com/alfuken/chunk_claim/issues/6?email_source=notifications\u0026email_token=AJSS6OFULFY3EU7FJICBSMDQVQ6MNA5CNFSM4JGPJIPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFD2SGQ#issuecomment-558344474",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MisterSmileyFace** [comment]
Also, is there an admin feature? I need to claim a ton of chunks for the spawn location, but I do not want everyone to be able to claim a ton of chunks. The only config I have found so far, changes it evenly for everyone. I just downloaded the new update and fingers crossed!!

**Comment by Szum123321** [comment]
You could set this number to high value, claim chunks and after that turn it down.

**Comment by alfuken** [comment]
@MisterSmileyFace you can also edit claims directly in the data file (<minecraft_folder>/data/chunk_claim.json), the format is pretty simple, just make 1 claim, then copy-paste a claim entry and change chunk coordinates, and that's it.
